#!/bin/sh
if [[ $1 == remove ]]; then
echo "### postrm starts ###"
echo "### removing documents ###"
rm -rf /var/mobile/Documents/Seeds
echo "### removing caches ###"
rm -rf /var/mobile/Library/Caches/com.simplelife.Seeds.*
echo "### removing preferences ###"
rm -rf /var/mobile/Library/Preferences/com.simplelife.Seeds.*
echo "### postrm ends ###"
declare -a cydia  
cydia=($CYDIA)  
if [[ ${CYDIA+@} ]]; then  
eval "echo 'finish:reload' >&${cydia[0]}"  
else  
echo "Please respring your device."  
fi
fi